import { ArrowRight, Building2, CheckCircle2, Clock3, Search, ShieldCheck, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { LiveJobPreview } from "@/components/live-job-preview";

export default function Home() {
  return <main className="min-h-screen bg-[#f4f8fb] text-slate-950"><SiteHeader/>
    <section className="relative overflow-hidden bg-[#0b3558] text-white"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_80%_20%,#20c5c9_0,transparent_32%),radial-gradient(circle_at_15%_90%,#286a9b_0,transparent_30%)]"/>
      <div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-20"><div className="flex flex-col justify-center"><Badge className="mb-6 border border-white/20 bg-white/10 px-3 py-1.5 text-white"><Sparkles/> Credential-first healthcare hiring</Badge><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-0.055em] sm:text-6xl lg:text-7xl">The right nurse.<br/><span className="text-[#5fe0d5]">The right shift.</span><br/>Right now.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-blue-100">Search verified opportunities from official healthcare employer sources or submit a staffing need.</p><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-blue-50"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#5fe0d5]"/> Live employer feed</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#5fe0d5]"/> Official requisition IDs</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#5fe0d5]"/> Direct applications</span></div></div>
        <div className="rounded-[2rem] border border-white/15 bg-white p-5 text-slate-950 shadow-2xl shadow-slate-950/30 sm:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-bold text-[#047f83]">VERIFIED OPPORTUNITIES</p><h2 className="mt-1 text-2xl font-black tracking-tight">Current nursing roles</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Live feed</span></div>
          <form action="/jobs" className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><label className="relative"><span className="sr-only">Role or location</span><Search className="absolute left-3 top-3.5 size-4 text-slate-400"/><Input name="q" className="h-11 rounded-xl pl-9" placeholder="Role, specialty, or city"/></label><Button className="h-11 rounded-xl bg-[#e5a327] px-5 text-slate-950 hover:bg-[#f0b33b]">Search</Button></form>
          <LiveJobPreview/>
          <Button asChild variant="outline" className="mt-4 h-11 w-full rounded-xl border-slate-300"><a href="/jobs">View all opportunities <ArrowRight/></a></Button>
        </div></div></section>
    <section className="mx-auto grid max-w-7xl gap-5 px-5 py-10 sm:grid-cols-3 lg:px-8">{[[ShieldCheck,"Verified source","Every listed role comes directly from Parkland Health’s official job feed."],[Clock3,"Current postings","Listings refresh automatically and show the employer’s published posting date."],[Building2,"Official application","Applicants continue on the employer’s secure Workday hiring site."]].map(([Icon,title,copy])=>{const ItemIcon=Icon as typeof ShieldCheck; return <div key={title as string} className="rounded-2xl border border-slate-200 bg-white p-6"><ItemIcon className="size-6 text-[#047f83]"/><h2 className="mt-4 text-lg font-extrabold">{title as string}</h2><p className="mt-2 leading-7 text-slate-600">{copy as string}</p></div>})}</section>
    <section id="how" className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#047f83]">How it works</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">Real roles. Official applications.</h2><p className="mt-4 leading-7 text-slate-600">NurseConnect displays live employer data and sends applicants to the employer’s own hiring system.</p></div><div className="grid gap-4 sm:grid-cols-3">{[["01","Search","Filter current Parkland Health nursing openings."],["02","Review","Check the requisition, posting date, location, and role details."],["03","Apply","Continue securely to Parkland’s official Workday application."]].map(([n,t,c])=><article key={n} className="rounded-2xl bg-[#f4f8fb] p-6"><span className="text-sm font-black text-[#047f83]">{n}</span><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-2 leading-7 text-slate-600">{c}</p></article>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid items-center gap-8 rounded-[2rem] bg-[#dff5f3] p-8 sm:p-12 lg:grid-cols-[1fr_auto]"><div><p className="font-bold text-[#047f83]">FOR HEALTHCARE FACILITIES</p><h2 className="mt-2 text-3xl font-black tracking-tight">Start with a complete staffing request.</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Give us the role, location, start date, opening count, and key requirements in one place.</p></div><Button asChild className="h-12 rounded-xl bg-[#0b3558] px-6"><a href="/facilities">Request staff <ArrowRight/></a></Button></div></section>
    <SiteFooter/></main>;
}
