import { ArrowRight, Building2, CheckCircle2, Clock3, MapPin, Search, ShieldCheck, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { jobs } from "@/lib/jobs";

export default function Home() {
  return <main className="min-h-screen bg-[#f4f8fb] text-slate-950"><SiteHeader/>
    <section className="relative overflow-hidden bg-[#0b3558] text-white"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_80%_20%,#20c5c9_0,transparent_32%),radial-gradient(circle_at_15%_90%,#286a9b_0,transparent_30%)]"/>
      <div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-20"><div className="flex flex-col justify-center"><Badge className="mb-6 border border-white/20 bg-white/10 px-3 py-1.5 text-white"><Sparkles/> Credential-first healthcare hiring</Badge><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-0.055em] sm:text-6xl lg:text-7xl">The right nurse.<br/><span className="text-[#5fe0d5]">The right shift.</span><br/>Right now.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-blue-100">Search clear opportunities or submit a staffing need from one focused healthcare hiring workspace.</p><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-blue-50"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#5fe0d5]"/> Structured credential details</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#5fe0d5]"/> Transparent rates</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#5fe0d5]"/> Direct applications</span></div></div>
        <div className="rounded-[2rem] border border-white/15 bg-white p-5 text-slate-950 shadow-2xl shadow-slate-950/30 sm:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-bold text-[#047f83]">OPEN OPPORTUNITIES</p><h2 className="mt-1 text-2xl font-black tracking-tight">Find your next shift</h2></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{jobs.length} current roles</span></div>
          <form action="/jobs" className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><label className="relative"><span className="sr-only">Role or location</span><Search className="absolute left-3 top-3.5 size-4 text-slate-400"/><Input name="q" className="h-11 rounded-xl pl-9" placeholder="Role, specialty, or city"/></label><Button className="h-11 rounded-xl bg-[#e5a327] px-5 text-slate-950 hover:bg-[#f0b33b]">Search</Button></form>
          <div className="mt-6 space-y-3">{jobs.slice(0,3).map((job)=><article key={job.id} className="rounded-2xl border border-slate-200 p-4 transition hover:border-[#1ba4a8] hover:shadow-lg"><div className="flex items-start justify-between gap-4"><div><h3 className="font-extrabold tracking-tight">{job.title}</h3><p className="mt-1 text-sm font-medium text-slate-500">{job.facility}</p></div><span className="rounded-lg bg-cyan-100 px-2.5 py-1 text-xs font-bold text-cyan-800">{job.type}</span></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm"><span className="flex items-center gap-1.5 text-slate-600"><MapPin className="size-4"/>{job.location}</span><span className="font-black text-[#0b3558]">{job.pay}</span></div></article>)}</div>
          <Button asChild variant="outline" className="mt-4 h-11 w-full rounded-xl border-slate-300"><a href="/jobs">View all opportunities <ArrowRight/></a></Button>
        </div></div></section>
    <section className="mx-auto grid max-w-7xl gap-5 px-5 py-10 sm:grid-cols-3 lg:px-8">{[[ShieldCheck,"Qualification clarity","Every application captures license, state, experience, and role-specific context."],[Clock3,"Faster intake","Nurses apply and facilities request coverage through forms that actually save records."],[Building2,"One useful view","Signed-in users can revisit their applications and staffing requests in a dashboard."]].map(([Icon,title,copy])=>{const ItemIcon=Icon as typeof ShieldCheck; return <div key={title as string} className="rounded-2xl border border-slate-200 bg-white p-6"><ItemIcon className="size-6 text-[#047f83]"/><h2 className="mt-4 text-lg font-extrabold">{title as string}</h2><p className="mt-2 leading-7 text-slate-600">{copy as string}</p></div>})}</section>
    <section id="how" className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#047f83]">How it works</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">Less friction. Better information.</h2><p className="mt-4 leading-7 text-slate-600">NurseConnect brings the first steps of staffing into one clear workflow without pretending that clinical verification or hiring decisions can be reduced to a button.</p></div><div className="grid gap-4 sm:grid-cols-3">{[["01","Search","Filter real openings by role, specialty, location, and work type."],["02","Submit","Apply or request staff with the details needed for a useful follow-up."],["03","Track","Use your private dashboard to see what you submitted and its current status."]].map(([n,t,c])=><article key={n} className="rounded-2xl bg-[#f4f8fb] p-6"><span className="text-sm font-black text-[#047f83]">{n}</span><h3 className="mt-4 text-xl font-black">{t}</h3><p className="mt-2 leading-7 text-slate-600">{c}</p></article>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid items-center gap-8 rounded-[2rem] bg-[#dff5f3] p-8 sm:p-12 lg:grid-cols-[1fr_auto]"><div><p className="font-bold text-[#047f83]">FOR HEALTHCARE FACILITIES</p><h2 className="mt-2 text-3xl font-black tracking-tight">Start with a complete staffing request.</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Give us the role, location, start date, opening count, and key requirements in one place.</p></div><Button asChild className="h-12 rounded-xl bg-[#0b3558] px-6"><a href="/facilities">Request staff <ArrowRight/></a></Button></div></section>
    <SiteFooter/></main>;
}
