export type Job = { id: string; title: string; facility: string; location: string; specialty: string; type: "Permanent" | "Travel" | "Per diem" | "Contract"; shift: string; pay: string; posted: string; description: string; requirements: string[] };

export const jobs: Job[] = [
  { id: "icu-rn-dallas", title: "ICU Registered Nurse", facility: "Northstar Medical Center", location: "Dallas, TX", specialty: "Critical Care", type: "Permanent", shift: "3×12 nights", pay: "$58–$66/hr", posted: "Today", description: "Join a high-acuity ICU team with strong charge-nurse support and modern clinical resources.", requirements: ["Active Texas RN license", "BLS and ACLS", "2+ years ICU experience"] },
  { id: "lvn-plano", title: "Licensed Vocational Nurse", facility: "Willow Creek Senior Living", location: "Plano, TX", specialty: "Long-Term Care", type: "Permanent", shift: "Day shift", pay: "$36–$42/hr", posted: "Today", description: "Provide resident-centered care in a stable day-shift role with a collaborative leadership team.", requirements: ["Active Texas LVN license", "BLS", "Long-term care experience preferred"] },
  { id: "travel-er-austin", title: "Travel RN · Emergency", facility: "Lone Star Regional", location: "Austin, TX", specialty: "Emergency", type: "Travel", shift: "13 weeks", pay: "$2,480/wk", posted: "1 day ago", description: "Fast-paced emergency assignment with guaranteed hours and a dedicated traveler onboarding team.", requirements: ["Compact or Texas RN license", "BLS, ACLS and PALS", "2+ years ED experience"] },
  { id: "or-rn-fort-worth", title: "Operating Room RN", facility: "Trinity Surgical Institute", location: "Fort Worth, TX", specialty: "Operating Room", type: "Contract", shift: "10-hour days", pay: "$62–$70/hr", posted: "1 day ago", description: "Support elective and urgent surgical cases in a streamlined, team-oriented operating suite.", requirements: ["Active RN license", "BLS", "Circulating experience"] },
  { id: "cna-arlington", title: "Certified Nursing Assistant", facility: "Greenview Rehabilitation", location: "Arlington, TX", specialty: "Rehabilitation", type: "Per diem", shift: "Flexible", pay: "$23–$27/hr", posted: "2 days ago", description: "Pick up flexible rehabilitation shifts with clear expectations and dependable scheduling.", requirements: ["Active CNA certification", "CPR certification", "6+ months experience"] },
  { id: "nicu-rn-houston", title: "NICU Registered Nurse", facility: "Gulf Children’s Hospital", location: "Houston, TX", specialty: "Neonatal", type: "Travel", shift: "12-hour nights", pay: "$2,720/wk", posted: "2 days ago", description: "Care for high-risk newborns in a Level III NICU with experienced clinical leadership.", requirements: ["Texas or compact RN license", "NRP and BLS", "2+ years Level III NICU"] },
  { id: "medsurg-san-antonio", title: "Medical-Surgical RN", facility: "Mission Valley Health", location: "San Antonio, TX", specialty: "Medical-Surgical", type: "Permanent", shift: "12-hour days", pay: "$49–$56/hr", posted: "3 days ago", description: "Build your practice on a supportive medical-surgical unit with structured development pathways.", requirements: ["Active Texas RN license", "BLS", "1+ year acute-care experience"] },
  { id: "don-irving", title: "Director of Nursing", facility: "Cypress Ridge Care Center", location: "Irving, TX", specialty: "Leadership", type: "Permanent", shift: "Full time", pay: "$128k–$148k", posted: "3 days ago", description: "Lead clinical operations, quality, staffing, and survey readiness for a respected skilled nursing center.", requirements: ["Active Texas RN license", "3+ years nurse leadership", "Skilled nursing experience"] },
];

export const specialties = Array.from(new Set(jobs.map((job) => job.specialty))).sort();
